[package]
name = "eniem"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.172"
nom = "8.0.0"
nom_locate = "5.0.0"

[features]
default = []
debug_interpreter = []
debug_parser = []
debug_main = []
debug_scopes = []
debug_memory = []

[dev-dependencies]
ntest = "0.9.3"
